# Generated by Django 6.0.1 on 2026-01-27 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
        ('designations', '0001_initial'),
        ('districts', '0001_initial'),
        ('projects', '0001_initial'),
        ('states', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subunit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('is_web', models.BooleanField(default=False)),
                ('is_app', models.BooleanField(default=False)),
                ('have_qc', models.BooleanField(default=False)),
                ('have_validation', models.BooleanField(default=False)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('qnr_schema', models.JSONField(blank=True, null=True)),
                ('lang_schema', models.JSONField(blank=True, null=True)),
                ('post_qc_validation_schema', models.JSONField(blank=True, null=True)),
                ('view_home_map', models.JSONField(default=dict)),
                ('filter_home_map', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subunit_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subunits', to='projects.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subunit_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subunits',
                'permissions': [('manage_subunit', 'Can manage subunits')],
            },
        ),
        migrations.CreateModel(
            name='SubunitTableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=255)),
                ('section_acronym', models.CharField(max_length=50)),
                ('table_name', models.CharField(max_length=255, unique=True)),
                ('fields', models.JSONField(default=list)),
                ('acronym_sequence', models.JSONField(default=list)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_subunit_table_mapping_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_mappings', to='subunits.subunittablemapping')),
                ('subunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_mappings', to='subunits.subunit')),
            ],
            options={
                'db_table': 'subunit_table_mappings',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SuRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('superiority', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subunits.subunit')),
            ],
        ),
        migrations.CreateModel(
            name='SuRoleHasPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subunits.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subunits.surole')),
            ],
        ),
        migrations.CreateModel(
            name='UserHasSuCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city')),
                ('subunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subunits.subunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHasSuDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designations.designation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHasSuDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='districts.district')),
                ('subunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subunits.subunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHasSuRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subunits.surole')),
                ('subunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subunits.subunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHasSuState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.state')),
                ('subunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subunits.subunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='subunit',
            constraint=models.UniqueConstraint(fields=('project', 'acronym'), name='unique_project_acronym'),
        ),
        migrations.AlterUniqueTogether(
            name='subunit',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='surolehaspermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='userhassurole',
            unique_together={('user', 'subunit')},
        ),
    ]
