# Generated by Django 6.0.1 on 2026-01-12 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subunit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('is_web', models.BooleanField(default=False)),
                ('is_app', models.BooleanField(default=False)),
                ('have_qc', models.BooleanField(default=False)),
                ('have_validation', models.BooleanField(default=False)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('qnr_schema', models.JSONField(blank=True, null=True)),
                ('lang_schema', models.JSONField(blank=True, null=True)),
                ('post_qc_validation_schema', models.JSONField(blank=True, null=True)),
                ('view_home_map', models.BooleanField(default=False)),
                ('filter_home_map', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subunit_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subunits', to='projects.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subunit_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subunits',
                'permissions': [('manage_subunit', 'Can manage subunits')],
            },
        ),
    ]
