# Generated by Django 6.0.1 on 2026-01-13 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subunits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubunitTableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=255)),
                ('section_acronym', models.CharField(max_length=50)),
                ('table_name', models.CharField(max_length=255, unique=True)),
                ('fields', models.JSONField(default=list)),
                ('acronym_sequence', models.JSONField(default=list)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_subunit_table_mapping_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_mappings', to='subunits.subunittablemapping')),
                ('subunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_mappings', to='subunits.subunit')),
            ],
            options={
                'db_table': 'subunit_table_mappings',
                'ordering': ['id'],
            },
        ),
    ]
