# Generated by Django 6.0.1 on 2026-01-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subunits', '0002_subunittablemapping'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE subunits
                ALTER COLUMN view_home_map DROP DEFAULT,
                ALTER COLUMN filter_home_map DROP DEFAULT;

                ALTER TABLE subunits
                ALTER COLUMN view_home_map TYPE jsonb
                    USING '{}'::jsonb,
                ALTER COLUMN filter_home_map TYPE jsonb
                    USING '{}'::jsonb;
            """,
            reverse_sql="""
                ALTER TABLE subunits
                ALTER COLUMN view_home_map TYPE boolean USING false,
                ALTER COLUMN filter_home_map TYPE boolean USING false;
            """
        )
    ]