# Generated by Django 6.0.1 on 2026-01-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subunits', '0004_alter_home_maps_to_json'),
    ]
    
    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE subunits
                ALTER COLUMN view_home_map SET DEFAULT '{}'::jsonb,
                ALTER COLUMN view_home_map SET NOT NULL,
                ALTER COLUMN filter_home_map SET DEFAULT '{}'::jsonb,
                ALTER COLUMN filter_home_map SET NOT NULL;

                UPDATE subunits
                SET view_home_map = '{}'::jsonb
                WHERE view_home_map IS NULL;

                UPDATE subunits
                SET filter_home_map = '{}'::jsonb
                WHERE filter_home_map IS NULL;
            """,
            reverse_sql="""
                ALTER TABLE subunits
                ALTER COLUMN view_home_map DROP NOT NULL,
                ALTER COLUMN filter_home_map DROP NOT NULL;
            """
        )
    ]
