# Generated by Django 6.0.1 on 2026-01-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='organization_id',
            new_name='project_id',
        ),
    ]
