# Generated by Django 6.0.1 on 2026-01-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
