# Generated by Django 6.0.1 on 2026-01-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0001_initial'),
        ('states', '0002_state_short_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('name', 'state')},
        ),
    ]
