# Generated by Django 6.0.1 on 2026-01-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'managed': True, 'ordering': ['name']},
        ),
    ]
