# Generated by Django 6.0.1 on 2026-01-30 11:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subunits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=255, unique=True)),
                ('question_type', models.CharField(choices=[('TEXT', 'Text'), ('TEXT_AREA', 'Text Area'), ('NUMBER', 'Number'), ('DROPDOWN', 'Dropdown'), ('RADIO', 'Radio'), ('CHECKBOX', 'Checkbox'), ('DATE', 'Date'), ('TIME', 'Time'), ('DATETIME', 'Date Time'), ('UPLOAD_IMAGE', 'Upload Image'), ('UPLOAD_FILE', 'Upload File'), ('LOCATION', 'Location'), ('SIGNATURE', 'Signature'), ('RATING', 'Rating'), ('SECTION', 'Section')], max_length=50)),
                ('label', models.TextField()),
                ('placeholder', models.TextField(blank=True, null=True)),
                ('q_number', models.CharField(blank=True, max_length=50, null=True)),
                ('properties', models.JSONField(default=dict)),
                ('options', models.JSONField(blank=True, default=list, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('view_home', models.BooleanField(default=False)),
                ('filter_home', models.BooleanField(default=False)),
                ('primary_view', models.BooleanField(default=False)),
                ('secondary_view', models.BooleanField(default=False)),
                ('view_index', models.IntegerField(blank=True, null=True)),
                ('home_label', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='surveys.dynamicquestion')),
                ('subunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='subunits.subunit')),
            ],
            options={
                'db_table': 'dynamic_questions',
                'ordering': ['view_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_type', models.CharField(choices=[('required', 'Required'), ('min_length', 'Minimum Length'), ('max_length', 'Maximum Length'), ('min_value', 'Minimum Value'), ('max_value', 'Maximum Value'), ('pattern', 'Regex Pattern'), ('email', 'Email'), ('phone', 'Phone'), ('date_format', 'Date Format'), ('multi_select', 'Multiple Selection'), ('custom', 'Custom Validation')], max_length=50)),
                ('value', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='surveys.dynamicquestion')),
            ],
            options={
                'db_table': 'field_validations',
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending_review', 'Pending Review')], default='draft', max_length=50)),
                ('submitted_data', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_by', to=settings.AUTH_USER_MODEL)),
                ('subunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='subunits.subunit')),
            ],
            options={
                'db_table': 'form_submissions',
            },
        ),
        migrations.CreateModel(
            name='SkipLogic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=10)),
                ('flag', models.BooleanField(default=True)),
                ('reverse_skip_logic', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skip_logic', to='surveys.dynamicquestion')),
            ],
            options={
                'db_table': 'skip_logic',
            },
        ),
        migrations.CreateModel(
            name='SkipLogicCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skip_logic_q', models.CharField(max_length=255)),
                ('skip_logic_val', models.CharField(max_length=255)),
                ('flag', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('skip_logic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='surveys.skiplogic')),
            ],
            options={
                'db_table': 'skip_logic_conditions',
            },
        ),
        migrations.CreateModel(
            name='SubmissionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True, null=True)),
                ('file_value', models.FileField(blank=True, null=True, upload_to='submissions/files/')),
                ('image_value', models.ImageField(blank=True, null=True, upload_to='submissions/images/')),
                ('json_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.dynamicquestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='surveys.formsubmission')),
            ],
            options={
                'db_table': 'submission_data',
            },
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['survey_id'], name='form_submis_survey__7e8ff9_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['status'], name='form_submis_status_c1f216_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['submitted_at'], name='form_submis_submitt_9c333e_idx'),
        ),
        migrations.AddIndex(
            model_name='submissiondata',
            index=models.Index(fields=['submission', 'question'], name='submission__submiss_18d380_idx'),
        ),
        migrations.AddIndex(
            model_name='submissiondata',
            index=models.Index(fields=['table_name', 'field_name'], name='submission__table_n_533a9b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submissiondata',
            unique_together={('submission', 'question')},
        ),
    ]
