# Generated by Django 6.0.1 on 2026-01-13 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_name', models.CharField(max_length=255)),
                ('draft_type', models.CharField(choices=[('auto_save', 'Auto Save'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('form_name', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=50)),
                ('version', models.CharField(default='1', max_length=20)),
                ('is_web', models.BooleanField(default=True)),
                ('is_app', models.BooleanField(default=True)),
                ('have_qc', models.BooleanField(default=True)),
                ('have_validation', models.BooleanField(default=True)),
                ('form_schema', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'form_drafts',
                'ordering': ['-updated_at'],
            },
        ),
    ]
